dependencies:
  - name: inventory-management-svc-mc
    version: 1.0.1-7
    repository: >-
      http://artifactory.mooc-two-iks-cluster.eu-gb.containers.appdomain.cloud/artifactory/example-repo-local/mooc-team-two
